roots = [
  "^Paths_",
  # App entry point (used by app/Main.hs)
  "^Sentinel.App.main$",
  # Custom prelude utilities
  "^Pre\\.",
  # Test suite (test/Main.hs)
  "^Main.main$",
]

type-class-roots = true

hie-directory = ".hie"
